[package]
name = "rust-json-parser"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_json_parser"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"], optional = true }
serde_json = { version = "1.0.151", optional = true }

[dev-dependencies]
criterion = "0.8.2"

[features]
python = ["pyo3", "serde_json"]
serde_json = ["dep:serde_json"]

[[bench]]
name = "parse_benchmark"
harness = false

[profile.bench]
debug = true
